# This is a basic workflow to help you get started with Actions

name: Storybook tests and documentation

# Controls when the workflow will run
on:
  pull_request:
    branches: [ dev, main]
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run interaction and accessibility tests
  interaction-and-accessibility:
    name: Interaction Test (Jest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
  # This workflow contains a single job called "build"
  build:
    name: Chromatic deployment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          node-version: '16.x'


      # Setup node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16.x'

      # GIT Config
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git://github.com/"' >> ~/.gitconfig

      # Setup quasar
      - name: Setup environment
        run: |
          yarn install
          

      # Build App
      - name: Deploy Chromatic
        uses: chromaui/action-next@v1
        env:
          APP_NAME: 'Hashed Portal Client'
          WSS: 'wss://n1.hashed.systems'
          BDK_SERVICES_URL: 'https://bdk.hashed.systems'
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          allowConsoleErrors: true
          node-version: '16.x'
        

